DROP TABLE IF EXISTS purchases CASCADE;

CREATE TABLE purchases (
  id SERIAL NOT NULL PRIMARY KEY,
  droid_id INTEGER NOT NULL REFERENCES droids(id) ON DELETE CASCADE,
  seller_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  buyer_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  sold_price INTEGER NOT NULL,
  sold_on DATE NOT NULL
);